export const FUSESWAP_SUBGRAPH_URL = 'https://api.thegraph.com/subgraphs/name/fuseio/fuseswap'

export const ETH_FUSE_AMB_SUBGRAPH_URL = process.env.REACT_APP_ETH_FUSE_AMB_SUBGRAPH_URL

export const FUSE_ETH_AMB_SUBGRAPH_URL = process.env.REACT_APP_FUSE_ETH_AMB_SUBGRAPH_URL

export const FUSE_BSC_AMB_SUBGRAPH_URL = process.env.REACT_APP_FUSE_BSC_AMB_SUBGRAPH_URL

export const BSC_FUSE_AMB_SUBGRAPH_URL = process.env.REACT_APP_BSC_FUSE_AMB_SUBGRAPH_URL

export const FUSE_ETH_NATIVE_BRIDGE_SUBGRAPH_URL = process.env.REACT_APP_FUSE_ETH_NATIVE_SUBGRAPH_URL

export const ETH_FUSE_NATIVE_BRIDGE_SUBGRAPH_URL = process.env.REACT_APP_ETH_FUSE_NATIVE_SUBGRAPH_URL
